const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { FrankfurterSDK } = require('../ts/dist/FrankfurterSDK.js');

async function main() {
  const requests = [];
  const client = new FrankfurterSDK({
    system: {
      fetch: async (url, options = {}) => {
        const timeout = AbortSignal.timeout(20000);
        const signal = options.signal ? AbortSignal.any([options.signal, timeout]) : timeout;
        const response = await fetch(url, { ...options, signal });
        requests.push({ url: String(url), status: response.status });
        return response;
      },
    },
  });
  const checks = [];
  const rate = (await client.Rate().load({ base: 'EUR', quote: 'USD' })).data();
  assert.equal(rate.base, 'EUR');
  assert.equal(rate.quote, 'USD');
  assert.match(rate.date, /^\d{4}-\d{2}-\d{2}$/);
  assert.ok(Number.isFinite(rate.rate) && rate.rate > 0);
  checks.push({ name: 'single pair via generated Rate.load', passed: true, response: rate });

  const identity = (await client.Rate().load({ base: 'EUR', quote: 'EUR' })).data();
  assert.equal(identity.rate, 1);
  checks.push({ name: 'same-currency identity rate', passed: true, response: identity });

  const currency = (await client.Currency().load({ id: 'EUR' })).data();
  assert.equal(currency.iso_code, 'EUR');
  assert.equal(typeof currency.name, 'string');
  checks.push({ name: 'currency details via generated Currency.load', passed: true, iso_code: currency.iso_code });

  let rejected = false;
  try { await client.Rate().load({ base: 'NOT_A_CURRENCY', quote: 'USD' }); }
  catch { rejected = true; }
  const status = requests.at(-1)?.status;
  assert.ok(rejected && status >= 400 && status < 500);
  checks.push({ name: 'invalid currency rejects and preserves HTTP failure', passed: true, status });

  const report = {
    checked_at_utc: new Date().toISOString(),
    node: process.version,
    sdk: 'FrankfurterSDK generated by Voxgig',
    authentication: 'No API key or account used',
    checks,
    requests,
  };
  const output = path.join(__dirname, '..', 'evidence', 'live-validation.json');
  fs.mkdirSync(path.dirname(output), { recursive: true });
  fs.writeFileSync(output, JSON.stringify(report, null, 2) + '\n');
  console.log(JSON.stringify(report, null, 2));
}

main().catch((error) => {
  console.error(JSON.stringify({ result: 'failed', name: error.name, message: error.message }));
  process.exitCode = 1;
});
